# Generated by Django 5.0.3 on 2024-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comp_name', models.CharField(max_length=120)),
                ('client_gst', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_country', models.CharField(max_length=50)),
                ('client_state', models.CharField(max_length=50)),
                ('client_pin', models.CharField(max_length=20)),
                ('client_other_info', models.TextField()),
                ('provider_comp_name', models.CharField(max_length=120)),
                ('provider_name', models.CharField(max_length=100)),
                ('provider_acc_no', models.CharField(max_length=100)),
                ('provider_bank_name', models.CharField(max_length=100)),
                ('provider_ifsc', models.CharField(max_length=50)),
                ('provider_gst', models.CharField(max_length=50)),
                ('provider_phone', models.CharField(max_length=20)),
                ('provider_mail', models.EmailField(max_length=254)),
                ('provider_other_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
