# Generated by Django 5.0.3 on 2024-03-26 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigne_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.clientserviceprovider')),
            ],
        ),
    ]
