# Generated by Django 5.0.3 on 2024-03-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.TextField(),
        ),
    ]
